<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class NewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('news')->insert([
            [
                'title' => 'Los viajes de la vicepresidenta Francia Márquez a África',
                'category' => 2,
                'slug' => 'los-viajes-de-la-vicepresidenta-francia-marquez-a-africa',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1695234406.pdf',
                'image' => '1695234406.jfif',
                'audio' => '1695234406.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-09-20 13:26:46'),
                'updated_at' => Carbon::parse('2023-09-20 13:26:46'),
                'deleted_at' => null,
                'deleted_at' => null,
            ],
            [
                'title' => '¿Por qué es importante mirar a África?',
                'category' => 2,
                'slug' => 'por-que-es-importante-mirar-a-africa',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1695242454.pdf',
                'image' => '1695242454.jpg',
                'audio' => '1695242454.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-09-20 15:40:54'),
                'updated_at' => Carbon::parse('2023-09-20 15:40:54'),
                'deleted_at' => null,
                'deleted_at' => null,
            ],
            [
                'title' => '“Las elecciones regionales en las dos Colombias ¿el voto del retroceso?”',
                'category' => 2,
                'slug' => 'las-elecciones-regionales-en-las-dos-colombias-el-voto-del-retroceso',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1695762876.pdf',
                'image' => '1695762875.webp',
                'audio' => '1695762875.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-09-26 16:14:36'),
                'updated_at' => Carbon::parse('2023-09-26 16:14:36'),
                'deleted_at' => null,
                'deleted_at' => null,
            ],
            [
                'title' => 'La construcción de la nación, para hacer parir la paz total.',
                'category' => 2,
                'slug' => 'la-construccion-de-la-nacion-para-hacer-parir-la-paz-total',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1696359328.pdf',
                'image' => '1696359328.png',
                'audio' => '1696359328.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-10-03 13:55:28'),
                'updated_at' => Carbon::parse('2023-10-03 13:55:28'),
                'deleted_at' => null,
            ],
            [
                'title' => 'La profecía bíblica, una ventana abierta al futuro de la humanidad',
                'category' => 1, // Añadido
                'slug' => 'la-profecia-biblica-una-ventana-abierta-al-futuro-de-la-humanidad',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692900373.pdf',
                'image' => '1692900373.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-01-31 18:02:13'),
                'updated_at' => Carbon::parse('2022-02-09 15:54:40'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Lo políticamente correcto',
                'category' => 1, // Añadido
                'slug' => 'lo-politicamente-correcto',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692900223.pdf',
                'image' => '1692900223.png',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-02-09 15:16:15'),
                'updated_at' => Carbon::parse('2022-02-09 15:51:22'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Lo políticamente correcto 2: Ciudadanos del cielo.',
                'category' => 1,
                'slug' => 'lo-politicamente-correcto-2-ciudadanos-del-cielo',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692900108.pdf',
                'image' => '1692900108.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-02-15 15:50:45'),
                'updated_at' => Carbon::parse('2022-03-03 17:47:30'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Lo políticamente correcto 3: El aborto, manifestación de la cuarta bestia.',
                'category' => 1,
                'slug' => 'lo-politicamente-correcto-3-el-aborto-manifestacion-de-la-cuarta-bestia',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692899954.pdf',
                'image' => '1692899954.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-03-02 17:21:52'),
                'updated_at' => Carbon::parse('2022-03-03 17:47:03'),
                'deleted_at' => null,
            ],
            [
                'title' => '¿Qué nos hace humanos?',
                'category' => 1,
                'slug' => 'que-nos-hace-humanos',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692755867.pdf',
                'image' => '1692755867.png',
                'audio' => '1692755867.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-06-28 16:49:35'),
                'updated_at' => Carbon::parse('2023-06-29 08:21:19'),
                'deleted_at' => null,
            ],
            [
                'title' => '¿Por qué una mirada desde el cielo?',
                'category' => 1,
                'slug' => 'por-que-una-mirada-desde-el-cielo',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692756077.pdf',
                'image' => '1692756077.png',
                'audio' => '1692756077.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-06-20 22:44:09'),
                'updated_at' => Carbon::parse('2023-06-20 22:44:09'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Recuperar nuestra memoria espiritual',
                'category' => 1,
                'slug' => 'recuperar-nuestra-memoria-espiritual',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692756184.pdf',
                'image' => '1692756184.png',
                'audio' => '1692756184.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-06-14 14:59:38'),
                'updated_at' => Carbon::parse('2023-06-14 14:59:38'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Ser tez brillante…, es una responsabilidad',
                'category' => 1,
                'slug' => 'ser-tez-brillante-es-una-responsabilidad',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692756356.pdf',
                'image' => '1692756356.png',
                'audio' => '1692756356.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-06-03 19:25:26'),
                'updated_at' => Carbon::parse('2023-06-03 19:25:26'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Negros, raizales, palenqueros…, ufffff',
                'category' => 1,
                'slug' => 'negros-raizales-palenqueros-ufffff',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692897556.pdf',
                'image' => '1692897556.jpeg',
                'audio' => '1692897556.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-10-05 21:07:24'),
                'updated_at' => Carbon::parse('2022-10-05 21:07:24'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Salud mental del pueblo de tez brillante',
                'category' => 1,
                'slug' => 'salud-mental-del-pueblo-de-tez-brillante',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692897817.pdf',
                'image' => '1692897817.jpg',
                'audio' => '1692897817.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-09-24 10:09:27'),
                'updated_at' => Carbon::parse('2022-09-24 10:09:27'),
                'deleted_at' => null,
            ],
            [
                'title' => '“Somos inmarcesibles"',
                'category' => 1,
                'slug' => 'somos-inmarcesibles',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692898027.pdf',
                'image' => '1692898026.jpg',
                'audio' => '1692898026.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-07-22 20:48:17'),
                'updated_at' => Carbon::parse('2022-07-23 08:48:08'),
                'deleted_at' => null,
            ],
            [
                'title' => '“Las dos Colombias”',
                'category' => 1,
                'slug' => 'las-dos-colombias',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692898269.pdf',
                'image' => '1692898269.webp',
                'audio' => '1692898269.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-06-22 18:21:55'),
                'updated_at' => Carbon::parse('2022-07-23 09:47:34'),
                'deleted_at' => null,
            ],
            [
                'title' => '“Soy de izquierda y ¿tu de derecha?”',
                'category' => 1,
                'slug' => 'soy-de-izquierda-y-tu-de-derecha',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692898427.pdf',
                'image' => '1692898427.jpg',
                'audio' => '1692898427.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-06-06 16:33:47'),
                'updated_at' => Carbon::parse('2022-07-23 09:53:25'),
                'deleted_at' => null,
            ],
            [
                'title' => '“El tiempo ¿Habrá tiempo en el cielo?”',
                'category' => 1,
                'slug' => 'el-tiempo-habra-tiempo-en-el-cielo',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692899488.pdf',
                'image' => '1692899488.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-05-03 15:28:04'),
                'updated_at' => Carbon::parse('2022-05-03 15:28:04'),
                'deleted_at' => null,
            ],
            [
                'title' => '“¿Los nadie o los hijos de Dios?”',
                'category' => 1,
                'slug' => 'los-nadie-o-los-hijos-de-dios',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692899611.pdf',
                'image' => '1692899611.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-03-28 21:23:40'),
                'updated_at' => Carbon::parse('2022-03-28 21:23:40'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Lo políticamente correcto 4: “Las cuatro bestias”',
                'category' => 1,
                'slug' => 'lo-politicamente-correcto-4-las-cuatro-bestias',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692899740.pdf',
                'image' => '1692899740.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-03-14 21:14:42'),
                'updated_at' => Carbon::parse('2022-04-06 07:43:01'),
                'deleted_at' => null,
            ],
            [
                'title' => '¿Negros o tez brillante?',
                'category' => 1,
                'slug' => 'negros-o-tez-brillante',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692755705.pdf',
                'image' => '1692755705.png',
                'audio' => '1692755705.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-07-06 17:27:58'),
                'updated_at' => Carbon::parse('2023-07-06 17:27:58'),
                'deleted_at' => null,
            ],
            [
                'title' => 'El alma tiene color',
                'category' => 1,
                'slug' => 'el-alma-tiene-color',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692755563.pdf',
                'image' => '1692755563.png',
                'audio' => '1692755563.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-07-14 19:06:42'),
                'updated_at' => Carbon::parse('2023-07-14 19:06:42'),
                'deleted_at' => null,
            ],
            [
                'title' => '¿Es la tez oscura, consecuencia del origen africano del hombre?',
                'category' => 1,
                'slug' => 'es-la-tez-oscura-consecuencia-del-origen-africano-del-hombre',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692755423.pdf',
                'image' => '1692755423.png',
                'audio' => '1692755423.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-07-27 11:17:19'),
                'updated_at' => Carbon::parse('2023-07-27 11:17:19'),
                'deleted_at' => null,
            ],
            [
                'title' => '¿La tez oscura, es consecuencia del origen celestial del hombre?',
                'category' => 1,
                'slug' => 'la-tez-oscura-es-consecuencia-del-origen-celestial-del-hombre',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692755196.pdf',
                'image' => '1692755196.png',
                'audio' => '1692755196.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-08-09 00:08:01'),
                'updated_at' => Carbon::parse('2023-08-09 00:08:01'),
                'deleted_at' => null,
            ],
            [
                'title' => 'Tres clases de habitantes en la tierra',
                'category' => 1,
                'slug' => 'tres-clases-de-habitantes-en-la-tierra',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1692900868.pdf',
                'image' => '1692900868.jpg',
                'audio' => null,
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2022-02-22 15:12:09'),
                'updated_at' => Carbon::parse('2022-02-22 15:12:09'),
                'deleted_at' => null,
            ],
            [
                'title' => '¿Fue el Reverendo Martin Luther King Jr. un líder político o un profeta de Dios?',
                'category' => 1,
                'slug' => 'fue-el-reverendo-martin-luther-king-jr-un-lider-politico-o-un-profeta-de-dios',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1695854214.pdf',
                'image' => '1695854214.png',
                'audio' => '1695854214.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-09-27 17:36:54'),
                'updated_at' => Carbon::parse('2023-09-27 17:36:54'),
                'deleted_at' => null,
            ],
            [
                'title' => '“La historia oculta, Israel huye a África”',
                'category' => 1,
                'slug' => 'la-historia-oculta-israel-huye-a-africa',
                'abstract' => 'Emancipación Cristiana Afro',
                'pdfdoc' => '1697765011.pdf',
                'image' => '1697765011.jpg',
                'audio' => '1697765011.mp3',
                'autor' => 'Henry Belalcázar Valencia',
                'created_at' => Carbon::parse('2023-10-19 20:23:31'),
                'updated_at' => Carbon::parse('2023-10-19 20:23:31'),
                'deleted_at' => null,
            ],
        ]);
    }
}
