services:
  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass_laravel
      MYSQL_DATABASE: eccav4
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - laravel_db_data:/var/lib/mysql
    networks:
      - proxy_network

  laravel_app:
    image: webdevops/php-apache:8.4
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      - laravel_db
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - ./:/app
    networks:
      - proxy_network

volumes:
  laravel_db_data:

networks:
  proxy_network:
    external: true
